import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Step-Ahead",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const additionalClassName = "app";
  return (
    <html lang="en">
      <body className={`${inter.className} ${additionalClassName}`}>
        {children}
      </body>
    </html>
  );
}
